version: "3.7"

services:
  base:
    build:
      context: .
      dockerfile: Dockerfile
    image: "base"
  main:
    build:
      context: ./main
      dockerfile: Dockerfile
    image: "main"
    networks:
      - main
    ports:
      - 80:3000
      - 8080:3443
    environment:
      - PORT=$SITE_PORT
      - YESOD_PORT=$SITE_YESOD_PORT
      - SQLITE_DATABASE=$SITE_DATABASE
      - ROBOT_PASS
    volumes:
      - ./main/app:/site/app
      - ./main/assets:/site/assets
      - ./main/config:/site/config
      - ./main/Layouts:/site/Layouts
      - ./main/src:/site/src
      - ./main/static:/site/static
      - ./main/templates:/site/templates
      - ./main/test:/site/test
      - database-volume:/site/database/
    stdin_open: true
    entrypoint: ["entrypoint.sh"]

volumes:
  database-volume:

networks:
  main:
